Repository uuid-rs/uuid, pull requests merged in 2018-06, with the labels that each got.

#259 Delete ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: Type: Meta

#262 update rand to 0.5.x
  Cargo.toml
  src/v4.rs
Labels: Release Notes, Type:Update Dependency

#268 make Uuid a newtype
  src/lib.rs
  src/ns.rs
  src/test_util.rs
  src/u128_support.rs
  src/v3.rs
  src/v5.rs
Labels: Type:Refactor
