Repository uuid-rs/uuid, pull requests merged in 2018-10, with the labels that each got.

#330 Add little-endian functions
  src/lib.rs
Labels: Release Notes, Type:Enhancement

#332 Add Uuid Builder
  src/builder.rs
  src/lib.rs
  src/prelude.rs
Labels: Hacktoberfest, Release Notes, Type:Enhancement

#337 remove slog test exclusion for 1.22.0 env
  .travis.yml
Labels: Hacktoberfest, Type: Duct Tape
