Repository uuid-rs/uuid, pull requests merged in 2018-02, with the labels that each got.

#143 Add minimum supported rustc version
  Cargo.toml
Labels: Pending:Review

#146 Update sha1 crate to 0.6.0
  Cargo.toml
Labels: Pending:Review

#148 updated toml to reflect uuid repo changes
  Cargo.toml
Labels: Pending:Merge

#149 Bors patch
  CODEOWNERS
Labels: Priority:High
