Repository uuid-rs/uuid, pull requests merged in 2018-05, with the labels that each got.

#214 remove `Uuid::new` function
  src/lib.rs
Labels: Breaking Change

#217 Update issue templates
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/ISSUE_TEMPLATE/feature
Labels: Type: Meta

#224 Use custom metadata to specify playground features
  Cargo.toml
Labels: Type:Refactor

#232 change nightly to const-fn feature gate
  .travis.yml
  Cargo.toml
  src/lib.rs
Labels: Channel:Nightly, Release Notes, Type:Refactor

#240 update serde and serde_test crates
  src/lib.rs
Labels: Type:Update Dependency

#245 Release: 0.6.4
  Cargo.toml
Labels: Tracker

#246 fix feature name
  src/lib.rs
Labels: Release Notes, Type:Bug

#247 prepare 0.6.5
  Cargo.toml
Labels: Tracker
