Repository uuid-rs/uuid, pull requests merged in 2018-03, with the labels that each got.

#161 released package as 0.6.1
  Cargo.toml
Labels: Tracker

#174 Temporarily disable clippy
  .travis.yml
Labels: Type: Meta

#172 from_rng_bytes added
  src/lib.rs
Labels: Type:Enhancement

#180 0.6.2 release update
  Cargo.toml
Labels: Tracker

#177 introduce the `uuid` prelude
  src/lib.rs
  src/slog_support.rs
Labels: Type:Enhancement

#187 Move namespaces into uuid::ns
  src/lib.rs
  src/ns.rs
Labels: Type:Refactor
